import os
import shutil

# Liste des chemins d'accès aux images
image_paths = [
    "dataset/coins_images/coins_images/all_coins/0992f9217f.jpg",
    "dataset/coins_images/coins_images/all_coins/1d5fb7f409.jpg",
    "dataset/coins_images/coins_images/all_coins/244d4d4639.jpg",
    "dataset/coins_images/coins_images/all_coins/2c8f0e58fb.jpg",
    "dataset/coins_images/coins_images/all_coins/35f856e199.jpg",
    "dataset/coins_images/coins_images/all_coins/41ee53b36e.jpg",
    "dataset/coins_images/coins_images/all_coins/44cf53bcde.jpg",
    "dataset/coins_images/coins_images/all_coins/49fd927d4c.jpg",
    "dataset/coins_images/coins_images/all_coins/4a4bd0f725.jpg",
    "dataset/coins_images/coins_images/all_coins/50e7fe98b7.jpg",
    "dataset/coins_images/coins_images/all_coins/5d6b82679d.jpg",
    "dataset/coins_images/coins_images/all_coins/681165d9f1.jpg",
    "dataset/coins_images/coins_images/all_coins/6d4d37ae2c.jpg",
    "dataset/coins_images/coins_images/all_coins/766f507935.jpg",
    "dataset/coins_images/coins_images/all_coins/7ce16206bb.jpg",
    "dataset/coins_images/coins_images/all_coins/87a1c3b8af.jpg",
    "dataset/coins_images/coins_images/all_coins/8e89dfa19b.jpg",
    "dataset/coins_images/coins_images/all_coins/9b1df4ab21.jpg",
    "dataset/coins_images/coins_images/all_coins/9bdccee820.jpg",
    "dataset/coins_images/coins_images/all_coins/aaf925663f.jpg",
    "dataset/coins_images/coins_images/all_coins/ae2a9d0217.jpg",
    "dataset/coins_images/coins_images/all_coins/b490ad931a.jpg",
    "dataset/coins_images/coins_images/all_coins/b65bf338f7.jpg",
    "dataset/coins_images/coins_images/all_coins/bb8b54822f.jpg",
    "dataset/coins_images/coins_images/all_coins/bd5e683f30.jpg",
    "dataset/coins_images/coins_images/all_coins/bd7c825ab5.jpg",
    "dataset/coins_images/coins_images/all_coins/c0ac04a0cf.jpg",
    "dataset/coins_images/coins_images/all_coins/d603d1e7e2.jpg",
    "dataset/coins_images/coins_images/all_coins/d74bf34efc.jpg",
    "dataset/coins_images/coins_images/all_coins/e893dcbca8.jpg",
    "dataset/coins_images/coins_images/all_coins/f8cc6f7201.jpg",
    "dataset/coins_images/coins_images/china_coins/06da1e60cc.jpg",
    "dataset/coins_images/coins_images/china_coins/0d0ac3a88a.jpg",
    "dataset/coins_images/coins_images/china_coins/12cacddb04.jpg",
    "dataset/coins_images/coins_images/china_coins/24bc5f6e9f.jpg",
    "dataset/coins_images/coins_images/china_coins/2f671c984f.jpg",
    "dataset/coins_images/coins_images/china_coins/4740a8da05.jpg",
    "dataset/coins_images/coins_images/china_coins/5c7495d3ca.jpg",
    "dataset/coins_images/coins_images/china_coins/5e4d27082b.jpg",
    "dataset/coins_images/coins_images/china_coins/6b8399d4e5.jpg",
    "dataset/coins_images/coins_images/china_coins/7689a78845.jpg",
    "dataset/coins_images/coins_images/china_coins/7dc2f1ef79.jpg",
    "dataset/coins_images/coins_images/china_coins/8a150b4bb6.jpg",
    "dataset/coins_images/coins_images/china_coins/a5c303f31d.jpg",
    "dataset/coins_images/coins_images/china_coins/aab9a625c4.jpg",
    "dataset/coins_images/coins_images/china_coins/ad4356b692.jpg",
    "dataset/coins_images/coins_images/china_coins/b545285cad.jpg",
    "dataset/coins_images/coins_images/china_coins/d70ec53e95.jpg",
    "dataset/coins_images/coins_images/china_coins/e42293fefb.jpg",
    "dataset/coins_images/coins_images/china_coins/f3648f78ff.jpg",
    "dataset/coins_images/coins_images/china_coins/f8b98b3770.jpg",
    "dataset/coins_images/coins_images/china_coins/fa9c3936ca.jpg",
    "dataset/coins_images/coins_images/euro_coins/026b6bf6ed.jpg",
    "dataset/coins_images/coins_images/euro_coins/04fb6c4fed.jpg",
    "dataset/coins_images/coins_images/euro_coins/0a030b6c5a.jpg",
    "dataset/coins_images/coins_images/euro_coins/1ee845b9ba.jpg",
    "dataset/coins_images/coins_images/euro_coins/20ebfe0b4b.jpg",
    "dataset/coins_images/coins_images/euro_coins/2f20e6f6a3.jpg",
    "dataset/coins_images/coins_images/euro_coins/35a1c45ae0.jpg",
    "dataset/coins_images/coins_images/euro_coins/40798eb414.jpg",
    "dataset/coins_images/coins_images/euro_coins/7f9dd7c082.jpg",
    "dataset/coins_images/coins_images/euro_coins/8a563f72c9.jpg",
    "dataset/coins_images/coins_images/euro_coins/91c23b8603.jpg",
    "dataset/coins_images/coins_images/euro_coins/969f9d387e.jpg",
    "dataset/coins_images/coins_images/euro_coins/b3f185cadd.jpg",
    "dataset/coins_images/coins_images/euro_coins/c0bd7b83a4.jpg",
    "dataset/coins_images/coins_images/euro_coins/defe0c372f.jpg",
    "dataset/coins_images/coins_images/indian_coins/021c3a3b47.jpg",
    "dataset/coins_images/coins_images/indian_coins/0b3270afd8.jpg",
    "dataset/coins_images/coins_images/indian_coins/105203c1fa.jpg",
    "dataset/coins_images/coins_images/indian_coins/13f2c1dfdf.jpg",
    "dataset/coins_images/coins_images/indian_coins/162d62e024.jpg",
    "dataset/coins_images/coins_images/indian_coins/2993f8fbec.jpg",
    "dataset/coins_images/coins_images/indian_coins/3a3d630d6a.jpg",
    "dataset/coins_images/coins_images/indian_coins/57ced878ff.jpg",
    "dataset/coins_images/coins_images/indian_coins/6fe09bf38f.jpg",
    "dataset/coins_images/coins_images/indian_coins/91e83a53ca.jpg",
    "dataset/coins_images/coins_images/indian_coins/96e18862f6.jpg",
    "dataset/coins_images/coins_images/indian_coins/9c0b6f75fe.jpg",
    "dataset/coins_images/coins_images/indian_coins/a59230ef5b.jpg",
    "dataset/coins_images/coins_images/indian_coins/af6072b73e.jpg",
    "dataset/coins_images/coins_images/indian_coins/b19f0410ae.jpg",
    "dataset/coins_images/coins_images/indian_coins/b47e7995b1.jpg",
    "dataset/coins_images/coins_images/indian_coins/c28327c953.jpg",
    "dataset/coins_images/coins_images/indian_coins/c8712c2c8d.jpg",
    "dataset/coins_images/coins_images/indian_coins/e5fc4d83a1.jpg",
    "dataset/coins_images/coins_images/indian_coins/f671cfbcc5.jpg",
    "dataset/coins_images/coins_images/peso_coins/16257f005f.jpg",
    "dataset/coins_images/coins_images/peso_coins/18e5daff24.jpg",
    "dataset/coins_images/coins_images/peso_coins/1e4b936e3a.jpg",
    "dataset/coins_images/coins_images/peso_coins/29d9c057db.jpg",
    "dataset/coins_images/coins_images/peso_coins/2a5edf5b8f.jpg",
    "dataset/coins_images/coins_images/peso_coins/382e9c61d2.jpg",
    "dataset/coins_images/coins_images/peso_coins/40ec550145.jpg",
    "dataset/coins_images/coins_images/peso_coins/5f1ac2f048.jpg",
    "dataset/coins_images/coins_images/peso_coins/a47eb7a8d1.jpg",
    "dataset/coins_images/coins_images/peso_coins/b078d19f0b.jpg",
    "dataset/coins_images/coins_images/peso_coins/c1ab7ae37f.jpg",
    "dataset/coins_images/coins_images/peso_coins/c4020f2ebb.jpg",
    "dataset/coins_images/coins_images/peso_coins/c9f52a349e.jpg",
    "dataset/coins_images/coins_images/peso_coins/dfbb7a8b53.jpg",
    "dataset/coins_images/coins_images/peso_coins/e75188df16.jpg",
    "dataset/coins_images/coins_images/us_coins/08f1f2f13c.jpg",
    "dataset/coins_images/coins_images/us_coins/1bf6e7be25.jpg",
    "dataset/coins_images/coins_images/us_coins/1fa0ef9061.jpg",
    "dataset/coins_images/coins_images/us_coins/2c8f0e58fb.jpg",
    "dataset/coins_images/coins_images/us_coins/34a00e3178.jpg",
    "dataset/coins_images/coins_images/us_coins/3b6bf8f4c7.jpg",
    "dataset/coins_images/coins_images/us_coins/69828182e8.jpg",
    "dataset/coins_images/coins_images/us_coins/979ea8e95e.jpg",
    "dataset/coins_images/coins_images/us_coins/c86fa6d3b6.jpg",
    "dataset/coins_images/coins_images/us_coins/eac92d0381.jpg",
    "dataset/coins_images/coins_images/yen_coins/182209e67d.jpg",
    "dataset/coins_images/coins_images/yen_coins/23c840f179.jpg",
    "dataset/coins_images/coins_images/yen_coins/2dbb4104d5.jpg",
    "dataset/coins_images/coins_images/yen_coins/34b27970d3.jpg",
    "dataset/coins_images/coins_images/yen_coins/3c32d6816f.jpg",
    "dataset/coins_images/coins_images/yen_coins/432ce0094b.jpg",
    "dataset/coins_images/coins_images/yen_coins/4d27842027.jpg",
    "dataset/coins_images/coins_images/yen_coins/4ed4743387.jpg",
    "dataset/coins_images/coins_images/yen_coins/522a707494.jpg",
    "dataset/coins_images/coins_images/yen_coins/6fdedc75bc.jpg",
    "dataset/coins_images/coins_images/yen_coins/79a88cbcc1.jpg",
    "dataset/coins_images/coins_images/yen_coins/7b2fcb5dfc.jpg",
    "dataset/coins_images/coins_images/yen_coins/82190ba644.jpg",
    "dataset/coins_images/coins_images/yen_coins/8910105010.jpg",
    "dataset/coins_images/coins_images/yen_coins/9742d5e9e3.jpg",
    "dataset/coins_images/coins_images/yen_coins/9f52d4c146.jpg",
    "dataset/coins_images/coins_images/yen_coins/a319848121.jpg",
    "dataset/coins_images/coins_images/yen_coins/a78251f564.jpg",
    "dataset/coins_images/coins_images/yen_coins/b4a9dcae76.jpg",
    "dataset/coins_images/coins_images/yen_coins/c49591d0c4.jpg",
    "dataset/coins_images/coins_images/yen_coins/c5f5b8cc36.jpg",
    "dataset/coins_images/coins_images/yen_coins/d27830b93a.jpg",
    "dataset/coins_images/coins_images/yen_coins/d8fdf027a8.jpg",
    "dataset/coins_images/coins_images/yen_coins/e23bc81a64.jpg",
    "dataset/coins_images/coins_images/yen_coins/e42baf7bc4.jpg",
    "dataset/coins_images/coins_images/yen_coins/e7279b8af6.jpg",
    "dataset/coins_images/coins_images/yen_coins/f8934b8498.jpg"
]


# Dossier de destination
destination_folder = "data_done"

# Créez le dossier de destination s'il n'existe pas
os.makedirs(destination_folder, exist_ok=True)

# Parcourir les chemins et copier les fichiers
for path in image_paths:
    if os.path.exists(path):
        # Nom du fichier
        file_name = os.path.basename(path)
        
        # Chemin de destination
        destination_path = os.path.join(destination_folder, file_name)
        
        # Copier le fichier
        shutil.copy(path, destination_path)
        print(f"Fichier {file_name} copié dans {destination_folder}")
    else:
        print(f"Chemin non trouvé : {path}")

print("Toutes les images ont été traitées.")